import { useEffect, useState } from 'react'
import { api } from './api'
import { useI18n } from './i18n'
type EncodingData=Awaited<ReturnType<typeof api.encoding>>
export default function Encoding(){
  const {t}=useI18n()
  const [L,setL]=useState(10),[point,setPoint]=useState(66),[data,setData]=useState<EncodingData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');api.encoding(L).then(v=>{if(!cancelled){setData(v);setLoading(false)}}).catch(e=>{if(!cancelled){setData(null);setError(String(e));setLoading(false)}});return()=>{cancelled=true}},[L])
  const x=data?.x[point]??null
  return <div className="encoding-page"><div className="section-head"><div><h2>{t('位置编码频谱')}</h2><p>{t('曲线由 Python 中已验证的 SinusoidalPositionalEncoding 实际输出。')}</p></div></div><div className="encoding-top"><div className="panel"><div className="slider-header"><h3>{t('位置编码带宽 L')}</h3><strong>{L}</strong></div><input aria-label={t('位置编码带宽 L')} type="range" min="0" max="15" value={L} onChange={e=>setL(Number(e.target.value))}/><div className="value-row"><div className="value-block"><span>{t('编码维度')}</span><strong>{data?.encoded_dim??t('暂无数据')}</strong></div><div className="value-block"><span>{t('最高频带')}</span><strong>{data?.highest_frequency_band??t('无')}</strong></div><div className="value-block"><span>{t('输入约定')}</span><strong>{data?.include_input===true?'True':t('暂无数据')}</strong></div></div></div><div className="panel formula-panel"><span>POSITION ENCODING</span><div>γ<sub>L</sub>(x)</div><code>3 + 6L = {data?.encoded_dim??'—'}</code><p>{t('每个频带增加正弦与余弦基信号；更高 L 加入更细的高频变化。这是编码器输出示意，不是训练测量值。')}</p></div></div><div className="panel"><div className="slider-header"><h3>{t('基信号 · x ∈ [0, 1]')}</h3><span>x = {x===null?t('暂无数据'):x.toFixed(3)}</span></div><input type="range" min="0" max="179" value={point} onChange={e=>setPoint(Number(e.target.value))} aria-label={t('采样位置 x')}/>{loading?<div className="empty-state">{t('正在从 Python 编码器读取曲线…')}</div>:error?<div className="empty-state"><strong>{t('编码曲线读取失败')}</strong><span>{error}</span></div>:L===0?<div className="empty-state"><strong>{t('L = 0，仅保留原始输入坐标')}</strong></div>:<div className="wave-grid">{data?.curves.map(curve=><div className="wave-card" key={curve.k}><div><strong>k {String(curve.k).padStart(2,'0')}</strong><span>2^{curve.k} πx</span></div><svg viewBox="0 0 360 90" preserveAspectRatio="none" role="img" aria-label={t('频带 {band} 的正弦和余弦',{band:curve.k})}><line x1="0" y1="45" x2="360" y2="45" stroke="#2a4537"/><line x1={point/179*360} y1="0" x2={point/179*360} y2="90" stroke="#d8fff0" opacity=".5"/><polyline fill="none" stroke="#8df8b5" strokeWidth="2" points={curve.sin.map((v,i)=>`${i/179*360},${45-v*32}`).join(' ')}/><polyline fill="none" stroke="#66c9c9" strokeWidth="1.5" points={curve.cos.map((v,i)=>`${i/179*360},${45-v*32}`).join(' ')}/></svg><div className="wave-values"><span>sin {curve.sin[point]?.toFixed(3)??'—'}</span><span>cos {curve.cos[point]?.toFixed(3)??'—'}</span></div></div>)}</div>}</div></div>
}
