export const copy = {
  en: {
    train: 'TRAIN', runs: 'RUNS', analyze: 'ANALYZE', system: 'SYSTEM',
    workstation: 'NEURAL RENDERING WORKSTATION', lab: 'RESEARCH INSTRUMENT / LOCAL',
    noRun: 'NO ACTIVE TRAINING', live: 'LIVE TRAINING', completed: 'TRAINING COMPLETE', interrupted: 'TRAINING INTERRUPTED',
    backend: 'BACKEND', online: 'ONLINE', offline: 'OFFLINE', connecting: 'CONNECTING',
    gpu: 'GPU', gpuReady: 'GPU READY', gpuUnavailable: 'GPU UNAVAILABLE', cpuMode: 'CPU FALLBACK',
    systemReady: 'SYSTEM READY', systemOffline: 'SYSTEM NOT READY', datasetReady: 'DATASET LOADED', datasetMissing: 'DATASET MISSING',
    setupTitle: 'Train a neural field.', setupSubtitle: 'One scene. Four essential controls. A new measured run begins when you launch.',
    quickSetup: 'QUICK EXPERIMENT SETUP', scene: 'SCENE', positionBandwidth: 'POSITIONAL BANDWIDTH', iterations: 'ITERATIONS', seed: 'RANDOM SEED',
    presets: 'QUICK PRESETS', demo: 'DEMO', standard: 'STANDARD', highQuality: 'HIGH QUALITY', custom: 'CUSTOM',
    demoDesc: '5K · short demonstration', standardDesc: '30K · research run', highDesc: '50K · extended run',
    advanced: 'ADVANCED PARAMETERS', baseline: 'OTHER VALUES FROM VALIDATED BASELINE',
    encoding: 'ENCODED DIMENSION', maxBand: 'MAX FREQUENCY BAND', parameters: 'MODEL PARAMETERS', estimate: 'architecture estimate',
    sceneInput: 'SCENE INPUT', groundTruth: 'GROUND TRUTH', reference: 'SAVED REFERENCE FRAME', noSceneImage: 'Input frame unavailable',
    sceneNote: 'LEGO synthetic dataset · fixed local source', launcher: 'EXPERIMENT LAUNCHER',
    start: 'START NEURAL TRAINING', starting: 'STARTING TRAINING', startUnavailable: 'CONNECT BACKEND TO START',
    startNote: 'Starts a real local training process. The configuration is frozen per run.',
    launchLock: 'LOCKING CONFIGURATION', launchRequest: 'ALLOCATING WORKER', launchWait: 'WAITING FOR TRAINER', launchDone: 'TRAINING STARTED',
    reconstruction: 'LIVE RECONSTRUCTION', latestSaved: 'LATEST SAVED PREVIEW', savedFrame: 'SAVED RECONSTRUCTION',
    previewPending: 'WAITING FOR FIRST PREVIEW', previewPendingBody: 'The trainer saves diagnostic previews at the configured interval. This viewport will update when a file is available.',
    previewKind: 'DIAGNOSTIC PREVIEW', evaluatedKind: 'FULL-VIEW EVALUATION', view: 'VIEW', validation: 'VALIDATION',
    iteration: 'ITERATION', timeMachine: 'TRAINING TIME MACHINE', timeMachineHint: 'Drag across saved reconstructions. Only measured frames are selectable.',
    noTimeline: 'NO SAVED FRAMES YET', returnLive: 'RETURN TO LATEST', checkpoints: 'CHECKPOINTS', snapshot: 'SNAPSHOT',
    telemetry: 'LIVE TELEMETRY', loss: 'LOSS', psnr: 'PSNR', ssim: 'SSIM', lpips: 'LPIPS', vram: 'VRAM', rays: 'RAYS / SEC',
    elapsed: 'ELAPSED', eta: 'ETA · EST.', gpuLoad: 'GPU LOAD', trainBatch: 'TRAINING RAY BATCH', fullView: 'FULL-VIEW EVALUATION',
    unavailable: 'UNAVAILABLE', notEvaluated: 'NOT EVALUATED', metricSource: 'Actual saved metrics only. PSNR during training is measured on a ray batch.',
    metrics: 'METRIC SIGNAL', lossChart: 'LOSS', psnrChart: 'PSNR · TRAIN BATCH', metricsView: 'EXPANDED METRICS', reset: 'RESET',
    stop: 'STOP SAFELY', resume: 'RESUME TRAINING', evaluate: 'EVALUATE CHECKPOINT', viewResults: 'VIEW RESULTS', newExperiment: 'NEW EXPERIMENT',
    runArchive: 'RUN ARCHIVE', runArchiveHint: 'Local experiment records · newest first', openRun: 'OPEN RUN',
    run: 'RUN', status: 'STATUS', date: 'DATE', noRuns: 'NO RUNS SAVED', noRunsBody: 'Start an experiment to create a local run record.',
    completedStatus: 'COMPLETED', runningStatus: 'TRAINING', stoppedStatus: 'STOPPED', failedStatus: 'FAILED', createdStatus: 'CREATED',
    analyzeTitle: 'Inspect the learning process.', analyzeSubtitle: 'Reconstruction, comparisons and measurements from saved files.',
    reconstructionTab: 'RECONSTRUCTION', compareTab: 'COMPARE', metricsTab: 'METRICS', encodingTab: 'ENCODING', samplingTab: 'SAMPLING',
    selectRun: 'SELECT A RUN', prediction: 'PREDICTION', difference: 'ABSOLUTE DIFFERENCE', compareNote: 'Same saved view and iteration. Missing images remain unavailable.',
    imageUnavailable: 'IMAGE NOT AVAILABLE', evaluationUnavailable: 'No full-view evaluation exists for this frame.',
    encodingTitle: 'POSITIONAL ENCODING', encodingNote: 'D = 3 + 6L · sin/cos(2^k πx), k = 0…L−1',
    spectralPreview: 'FREQUENCY BANDS', sceneGeometry: 'SCENE GEOMETRY',
    samplingTitle: 'RAY SAMPLING', samplingNote: 'Saved diagnostics and backend ray inspection.',
    machine: 'MACHINE', logs: 'LOGS', settings: 'SETTINGS',
    systemTitle: 'Machine telemetry.', systemSubtitle: 'Direct readings from the local runtime. Missing sensors are shown as unavailable.',
    gpuName: 'GRAPHICS PROCESSOR', temperature: 'TEMPERATURE', power: 'POWER', cuda: 'CUDA', pytorch: 'PYTORCH', cpu: 'CPU', ram: 'RAM',
    utilization: 'UTILIZATION', memoryUsed: 'MEMORY USED', runtime: 'RUNTIME', activity: 'GPU ACTIVITY',
    runLogs: 'RUN LOGS', noLogs: 'NO LOGS RECORDED', playBoot: 'PLAY BOOT SEQUENCE', skipBoot: 'SKIP BOOT SEQUENCE',
    bootPreference: 'Choose the startup animation for future launches.', language: 'LANGUAGE',
    presentation: 'PRESENTATION MODE', exitPresentation: 'EXIT PRESENTATION', fullscreen: 'FULLSCREEN',
    presentationHint: 'Input scene → positional encoding → training → reconstruction',
    showLogs: 'VIEW LOG', return: 'RETURN', retry: 'RETRY CONNECTION',
    noConnection: 'The research backend is offline.', noConnectionBody: 'Restart the desktop app or start the local backend, then retry.',
    loading: 'READING EXPERIMENT DATA', loadingRenderer: 'INITIALIZING RENDERER', loadingCheckpoint: 'LOADING CHECKPOINT',
    evaluating: 'EVALUATING VIEW', actionFailed: 'ACTION FAILED',
    advancedBatch: 'BATCH SIZE', advancedLearning: 'LEARNING RATE', advancedCheckpoints: 'CHECKPOINT INTERVAL', advancedPreview: 'PREVIEW INTERVAL',
    advancedDepth: 'NETWORK DEPTH', advancedWidth: 'NETWORK WIDTH', advancedDirection: 'DIRECTION ENCODING L', advancedRender: 'RENDER CHUNK SIZE',
    close: 'CLOSE', minimize: 'MINIMIZE', maximize: 'MAXIMIZE', restore: 'RESTORE',
    bootInit: 'INITIALIZING NERF RESEARCH CONSOLE', bootCuda: 'CHECKING CUDA DEVICE', bootTorch: 'CONNECTING PYTORCH RUNTIME',
    bootManifest: 'LOADING EXPERIMENT MANIFEST', bootCheckpoints: 'INDEXING CHECKPOINTS', bootRender: 'INITIALIZING RENDER PIPELINE',
    bootGpu: 'GPU DEVICE DETECTED', bootReady: 'NEURAL FIELD READY', bootOnline: 'SYSTEM ONLINE', skip: 'SKIP',
  },
  zh: {
    train: '训练', runs: '运行档案', analyze: '分析', system: '系统',
    workstation: '神经渲染研究工作站', lab: '研究仪器 / 本地运行',
    noRun: '当前没有训练', live: '实时训练中', completed: '训练完成', interrupted: '训练中断',
    backend: '后端', online: '在线', offline: '离线', connecting: '连接中',
    gpu: '显卡', gpuReady: 'GPU 已就绪', gpuUnavailable: 'GPU 不可用', cpuMode: 'CPU 后备模式',
    systemReady: '系统就绪', systemOffline: '系统尚未就绪', datasetReady: '数据集已载入', datasetMissing: '数据集缺失',
    setupTitle: '训练一个神经场。', setupSubtitle: '一个场景、四项关键设置。点击启动后创建真实的实验运行。',
    quickSetup: '快速实验设置', scene: '场景', positionBandwidth: '位置编码带宽', iterations: '迭代次数', seed: '随机种子',
    presets: '快速预设', demo: '演示', standard: '标准', highQuality: '高质量', custom: '自定义',
    demoDesc: '5K · 简短演示', standardDesc: '30K · 研究运行', highDesc: '50K · 完整运行',
    advanced: '高级参数', baseline: '其余参数取自已验证基准配置',
    encoding: '编码维度', maxBand: '最高频带', parameters: '模型参数量', estimate: '按网络结构计算',
    sceneInput: '场景输入', groundTruth: '真实图像', reference: '已保存的参考帧', noSceneImage: '输入帧不可用',
    sceneNote: 'LEGO 合成数据集 · 固定本地来源', launcher: '实验启动器',
    start: '开始神经网络训练', starting: '正在启动训练', startUnavailable: '连接后端后可启动',
    startNote: '启动真实的本地训练进程；每次运行的配置都会冻结。',
    launchLock: '正在冻结配置', launchRequest: '正在分配工作进程', launchWait: '等待训练器响应', launchDone: '训练已启动',
    reconstruction: '实时重建', latestSaved: '最新保存预览', savedFrame: '已保存的重建',
    previewPending: '等待首张预览图', previewPendingBody: '训练器会按已配置的间隔保存诊断预览。文件生成后这里会自动更新。',
    previewKind: '诊断预览', evaluatedKind: '全图评估', view: '视角', validation: '验证集',
    iteration: '迭代', timeMachine: '训练时间机器', timeMachineHint: '拖动查看已保存重建。只能选择真实存在的图像。',
    noTimeline: '尚无保存的图像', returnLive: '返回最新画面', checkpoints: '检查点', snapshot: '快照',
    telemetry: '实时遥测', loss: '损失', psnr: 'PSNR', ssim: 'SSIM', lpips: 'LPIPS', vram: '显存', rays: '射线 / 秒',
    elapsed: '已用时间', eta: '预计剩余', gpuLoad: 'GPU 负载', trainBatch: '训练射线批次', fullView: '全图评估',
    unavailable: '暂无数据', notEvaluated: '尚未评估', metricSource: '仅显示已保存的真实指标。训练 PSNR 来自射线批次。',
    metrics: '指标信号', lossChart: '损失', psnrChart: 'PSNR · 训练批次', metricsView: '扩展指标', reset: '重置',
    stop: '安全停止', resume: '恢复训练', evaluate: '评估检查点', viewResults: '查看结果', newExperiment: '新建实验',
    runArchive: '运行档案', runArchiveHint: '本地实验记录 · 最新优先', openRun: '打开运行',
    run: '运行', status: '状态', date: '日期', noRuns: '暂无保存的运行', noRunsBody: '启动实验后会在本地创建运行记录。',
    completedStatus: '已完成', runningStatus: '训练中', stoppedStatus: '已停止', failedStatus: '失败', createdStatus: '待启动',
    analyzeTitle: '观察模型如何学习。', analyzeSubtitle: '从已保存文件查看重建、对比与测量。',
    reconstructionTab: '重建', compareTab: '对比', metricsTab: '指标', encodingTab: '位置编码', samplingTab: '采样',
    selectRun: '选择运行', prediction: '预测图', difference: '绝对差异', compareNote: '同一已保存视角与迭代；缺失图像会明确标出。',
    imageUnavailable: '图像不可用', evaluationUnavailable: '此帧没有全图评估结果。',
    encodingTitle: '位置编码', encodingNote: 'D = 3 + 6L · sin/cos(2^k πx)，k = 0…L−1',
    spectralPreview: '频带', sceneGeometry: '场景几何',
    samplingTitle: '射线采样', samplingNote: '已保存的诊断图与后端射线检查。',
    machine: '机器', logs: '日志', settings: '设置',
    systemTitle: '机器遥测。', systemSubtitle: '直接读取本地运行时；无法读取的传感器显示暂无数据。',
    gpuName: '图形处理器', temperature: '温度', power: '功耗', cuda: 'CUDA', pytorch: 'PYTORCH', cpu: 'CPU', ram: '内存',
    utilization: '利用率', memoryUsed: '已用显存', runtime: '运行时', activity: 'GPU 活动',
    runLogs: '运行日志', noLogs: '暂无日志', playBoot: '播放启动动画', skipBoot: '跳过启动动画',
    bootPreference: '决定之后打开应用时是否播放初始化序列。', language: '语言',
    presentation: '演示模式', exitPresentation: '退出演示', fullscreen: '全屏',
    presentationHint: '输入场景 → 位置编码 → 网络训练 → 图像重建',
    showLogs: '查看日志', return: '返回', retry: '重试连接',
    noConnection: '研究后端当前离线。', noConnectionBody: '重新打开桌面应用或启动本地后端，再重试连接。',
    loading: '正在读取实验数据', loadingRenderer: '正在初始化渲染器', loadingCheckpoint: '正在加载检查点',
    evaluating: '正在评估视角', actionFailed: '操作失败',
    advancedBatch: '批量大小', advancedLearning: '学习率', advancedCheckpoints: '检查点间隔', advancedPreview: '预览间隔',
    advancedDepth: '网络深度', advancedWidth: '网络宽度', advancedDirection: '方向编码 L', advancedRender: '渲染分块大小',
    close: '关闭', minimize: '最小化', maximize: '最大化', restore: '还原',
    bootInit: '正在初始化 NeRF Research Console', bootCuda: '正在检查 CUDA 设备', bootTorch: '正在连接 PyTorch 运行时',
    bootManifest: '正在载入实验清单', bootCheckpoints: '正在索引检查点', bootRender: '正在初始化渲染管线',
    bootGpu: '已检测到 GPU 设备', bootReady: '神经场就绪', bootOnline: '系统上线', skip: '跳过',
  },
} as const

export type WorkstationCopy = { [K in keyof typeof copy.en]: string }
