batch_size: 256
checkpoint_interval: 250
dataset_root: data/nerf_synthetic
density_initial_bias: 0.1
direction_encoding_L: 4
far: 6.0
image_resolution: original
learning_rate: 0.0005
learning_rate_decay_factor: 0.1
learning_rate_decay_steps: 250000
near: 2.0
network_depth: 8
network_width: 256
normalize_ray_directions: false
num_coarse_samples: 64
num_fine_samples: 128
position_encoding_L: 10
preview_height: 100
preview_interval: 250
preview_width: 100
progress_interval: 25
random_seed: 0
ray_chunk_size: 128
render_chunk_size: 256
scene: lego
skip_connection_layer: 4
training_iterations: 500
view_width: 128
white_background: true
